// pages/api/generateNote.ts

import type { NextApiRequest, NextApiResponse } from 'next';
import { OpenAI } from 'openai';

// Initialize OpenAI with your API key
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { prompt } = req.body;

  if (!prompt || typeof prompt !== 'string') {
    return res.status(400).json({ error: 'Invalid prompt' });
  }

  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-3.5-turbo',
      messages: [
        {
          role: 'system',
          content: `
You are an experienced clinician generating progress notes.
Use a single, cohesive paragraph in the third person.
Focus on observed behaviors and significant changes without referencing numerical scores.
Employ qualitative descriptors to convey intensity and engagement levels.
Conclude with one key clinical insight or recommendation.
Keep the note between 150-200 words.
Avoid bullet points and ensure the narrative flows naturally.
        `,
        },
        {
          role: 'user',
          content: prompt,
        },
      ],
      max_tokens: 400, // Adjusted to control the length
      temperature: 0.7, // Balanced creativity and coherence
      top_p: 1,
      frequency_penalty: 0,
      presence_penalty: 0,
    });

    const generatedNote = response.choices[0]?.message?.content?.trim();

    if (!generatedNote) {
      throw new Error('No content generated by OpenAI');
    }

    res.status(200).json({ generatedNote });
  } catch (error: any) {
    console.error('Error generating note:', error);
    res.status(500).json({ error: 'Failed to generate note' });
  }
}
